FROM golang:latest as builder

WORKDIR /usr/app/desafio_go

COPY /codigo/ /usr/app/desafio_go

RUN go build .

FROM scratch

COPY --from=builder /usr/app/desafio_go .

ENTRYPOINT [ "./desafio_go" ]